name: Replace ALB URL

on: [push]

jobs:
 replace_alb_url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace ALB URL
      run: |
        ALB_URL_A="blue.url"
        ALB_URL_B="green.url"

        sed -i "s|$ALB_URL_A|$ALB_URL_B|g" config.file

    - name: Commit changes
      run: |
        git config --local user.email "venkatesh.sarivisetty015@github.com"
        git config --local user.name "venkatesh.sarivisetty"
        git add config.file
        git commit -m "Replace ALB URL"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
